### PR TITLE
Welcome Folder Translations and basic/memory translation

### PR DESCRIPTION
**Pull request by zek**

### CODE REVIEW

**Comment by wilzbach** [comment]
> and basic/memory translation

@drtzack While it's awesome to see you so productive, we have experienced before that large PRs are less likely to get reviewed. Hence I recommend to open a PR for every file to avoid that your work gets stalled. Does this sound reasonable to you?
Btw in case you use a Posix system and are lazy, I wrote a simple helper that automates submitting multiple PRs:

https://github.com/wilzbach/splitup-prs

It's also described here:

https://github.com/stonemaster/dlang-tour/wiki/Tips-for-translators

(in short: with individual PRs there is no pressure to change `index.yml` directly as it will only create conflicts, `splitup-prs` will take care of this automatically).

**Comment by zek** [comment]
OK I will create a pull-request like you said :)

**Comment by wilzbach** [comment]
> OK I will create a pull-request like you said :)

Let me/us know if you run into troubles!

**Comment by wilzbach** [comment]
> > OK I will create a pull-request like you said :)
> > Let me/us know if you run into troubles!

Btw in case it helps I improved the detection of the upstream branch a bit and added a short tutorial:

https://github.com/wilzbach/splitup-prs#using-with-an-existing-commit

**Pull request closed without merging**
